### PR TITLE
Additions for MapProxy and GDAL 1.11.2

### PR DESCRIPTION
**Pull request by BobTorgerson**
Modification to automation script to install MapProxy and install the OSM Humanitarian tile layer configuration for MapProxy. 

Also, installs GDAL 1.11.2 along with the GeoNode 2.4.x branch from our fork of GeoNode.

---

This change is [Reviewable](https://reviewable.io/reviews/ua-snap/vagrant-geonode/41)

### CODE REVIEW

**Comment by brucecrevensten** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[automation.sh, line 129 [r1]](https://reviewable.io:443/reviews/ua-snap/vagrant-geonode/41#-KITtQQb5jIiaObn9N3b:-KITtQQcf48ZMX4X9RG-:111738511) ([raw file](https://github.com/ua-snap/vagrant-geonode/blob/b77426499a6f428e1d3930f1890d7596c4f07f9b/automation.sh#L129)):_

> ``` Shell
> pip install -e geonode
> 
> # Download and untar the GDAL 1.11.2 Python package
> ```

I wondered if 11.4 has stuff we obviously want "solves all problems with Arctic projections" -- it doesn't.  11.2 is good!

---

_[README.md, line 204 [r1]](https://reviewable.io:443/reviews/ua-snap/vagrant-geonode/41#-KITtH3euiI6-nFiXHK5:-KITtH3euiI6-nFiXHK6:-1132183814) ([raw file](https://github.com/ua-snap/vagrant-geonode/blob/b77426499a6f428e1d3930f1890d7596c4f07f9b/README.md#L204)):_

> ``` Markdown
> 
> ```
> 
>    http://localhost:8888/demo/?tms_layer=osm&format=png&srs=EPSG%3A3857
> 
> ```
> ```

Good clean docs + how to use + prove its working.  Nice.

---

_[Vagrantfile, line 28 [r1]](https://reviewable.io:443/reviews/ua-snap/vagrant-geonode/41#-KITt7UUoPXmYB0CvFqw:-KITt7UUoPXmYB0CvFqx:1523506398) ([raw file](https://github.com/ua-snap/vagrant-geonode/blob/b77426499a6f428e1d3930f1890d7596c4f07f9b/Vagrantfile#L28)):_

> ``` Ruby
>   config.vm.network "forwarded_port", guest: 8000, host: 8000
>   config.vm.network "forwarded_port", guest: 8080, host: 8080
>   config.vm.network "forwarded_port", guest: 8888, host: 8888
> ```

we picked the same port!  :+1: 

---

_[geonode/.gitignore, line 14 [r1]](https://reviewable.io:443/reviews/ua-snap/vagrant-geonode/41#-KITslEKHLngvN7EiHbO:-KITslEKHLngvN7EiHbP:-797672036) ([raw file](https://github.com/ua-snap/vagrant-geonode/blob/b77426499a6f428e1d3930f1890d7596c4f07f9b/geonode/.gitignore#L14)):_

> ```
> !NCEP/temp_color_k.txt
> !NCEP/temp_color_c.txt
> !mapventure-mapproxy.yaml
> ```

What's your thinking on why this file should be ignored?  My first gut feel here is, "its configuration we should version control it!"

---

_[geonode/mapventure-mapproxy.yaml, line 40 [r1]](https://reviewable.io:443/reviews/ua-snap/vagrant-geonode/41#-KITsyx4z-lPHNcBO9il:-KITsyx4z-lPHNcBO9im:271176009) ([raw file](https://github.com/ua-snap/vagrant-geonode/blob/b77426499a6f428e1d3930f1890d7596c4f07f9b/geonode/mapventure-mapproxy.yaml#L40)):_

> ``` YAML
> grids:
>     webmercator:
>         base: GLOBAL_WEBMERCATOR                        
> ```

trailing whitespace is my fault, need to remove this before merging

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/ua-snap/vagrant-geonode/41)_

**Comment by BobTorgerson** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[geonode/.gitignore, line 14 [r1]](https://reviewable.io:443/reviews/ua-snap/vagrant-geonode/41#-KITslEKHLngvN7EiHbO:-KITu8SV_qhW2nuHQVsd:-1219874206) ([raw file](https://github.com/ua-snap/vagrant-geonode/blob/b77426499a6f428e1d3930f1890d7596c4f07f9b/geonode/.gitignore#L14)):_
<details><summary>

<i>Previously, brucecrevensten (Bruce Crevensten) wrote…</i></summary>



> What's your thinking on why this file should be ignored?  My first gut feel here is, "its configuration we should version control it!"
> </details>
> The ! represents that it is not ignored when placed into the gitignore file. I do think that this configuration file should be in source control, and it is :)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/ua-snap/vagrant-geonode/41)_

**Comment by brucecrevensten** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[geonode/.gitignore, line 14 [r1]](https://reviewable.io:443/reviews/ua-snap/vagrant-geonode/41#-KITslEKHLngvN7EiHbO:-KITyAhaYIdqQANwjWKF:-269963027) ([raw file](https://github.com/ua-snap/vagrant-geonode/blob/b77426499a6f428e1d3930f1890d7596c4f07f9b/geonode/.gitignore#L14)):_
<details><summary>

<i>Previously, BobTorgerson wrote…</i></summary>



> The ! represents that it is not ignored when placed into the gitignore file. I do think that this configuration file should be in source control, and it is :)
> </details>
> My goof!!  :)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/ua-snap/vagrant-geonode/41)_

**Comment by brucecrevensten** [comment]
Reviewed 1 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/ua-snap/vagrant-geonode/41)_

**Pull request merged**
